version: "1"

locale: "ru"

models:
  - path: "some_path"
    fields:
      - name: "email"
        processor: "email"
      - name: "name"
        processor: "name"
      - name: "inn"
        processor: "inn"

  - path: "another_path"
    fields:
      - name: "name"
        processor: "name"